### ISSUE TITLE
Warning: Unable to find required IndoorAtlas SDK native libraries. Please check integration instructions.

### ISSUE THREAD

**Issue by ronaldgalangy** [IndoorAtlas/android-sdk-examples#20]
I run my app, in these following devices :
- Samsung S7 (Marshmallow) :+1: 
- Samsung J2 (Lollipop) :+1: 
- Asus Zenfone 2 (Lollipop) :-1:  (app crash)

The crash happen when I add [realm](http://realm.io/) database as library dependency.

Here is the crash log
![issue_ia](https://cloud.githubusercontent.com/assets/8153347/22411858/50ccb7a0-e6e3-11e6-89e1-fa3a031b1d63.jpg)

Here is my gradle dependency :
```
compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    compile "com.indooratlas.android:indooratlas-android-sdk:$ia_version"
    compile "com.davemorrissey.labs:subsampling-scale-image-view:$scaleimage_version"

    compile "io.reactivex:rxjava:$rxjava_version"
    compile "io.reactivex:rxandroid:$rxandroid_version"

    compile "com.squareup.retrofit2:retrofit:$retrofit_version"
    compile "com.squareup.retrofit2:converter-gson:$retrofit_version"
    compile "com.squareup.retrofit2:adapter-rxjava:$retrofit_version"

    compile "com.github.bumptech.glide:glide:$glide_version"
```

Anyone here, encounter the same issue?

**Comment by jraanamo** [comment]
Hi,

We did a small test and ran realm.io together with our SDK in emulator with x86_64 image and encountered no issues. I suspect, that for some reason on your Asus, a 32bit version of Realm native library is selected and since IndoorAtlas SDK does not come with 32bit x86 native library - our library does not get loaded and the result is the crash you saw. As far as I know, your Asus device should be 64bit so I am not sure why the conflict. Maybe you could do some debugging to see which architectures get loaded?
