### ISSUE TITLE
Accuracy Issues 

### ISSUE THREAD

**Issue by ParasVirdi** [IndoorAtlas/android-sdk-examples#44]
We have implemented all the steps:
        1. Imposing Map on Indoor Atlas Cloud
        2. Mapping using Map Creator2
        3. Wayfinding etc.
     
We are building app for blind people for navigation but after building whole app accuracy is not upto the mark.(not even 2 meters)

Issues :

1.Initial Location while starting navigation process is not accurate, we need to walk some distance to get initial location.
2.In the process of navigation that we are implementing using wayfinding ,is also not coming accurate and not even 2 meters that you claimed.
3.Sometimes while navigation, blue dot goes out of the building.

Kindly Help!

**Comment by jraanamo** [comment]
Since this is more a question about mapping/service quality and not about the examples or APIs - please submit your support request to support@indooratlas.com. But before you do, please carefully read the documentation related to how to do mapping, especially this page: https://docs.indooratlas.com/map/recording-paths/basic-recording-tutorial/. Mapping needs to be of high quality in order for the service to provide best possible performance.
